### ISSUE TITLE
Crashes when opening in Expo app

### ISSUE THREAD

**Issue by Traviskn** [EvanBacon/Expo-Voxel#8]
I've been trying to open this in the latest version of the Expo app (iPhone 6), but it crashes on the loading screen. This project looks very cool and I'd love to be able to test it out!

**Comment by EvanBacon** [comment]
Odd, I just ran it on my iPhone 7 plus. Have you tried running it in a simulator?

**Comment by Traviskn** [comment]
Yeah I just gave the simulator a try, (running the project in XDE).  It gets past the loading screen and renders an initial view of the terrain, but is unresponsive.  In the XDE logs I see a few error messages: 

```
THREE.WebGLRenderer 85
9:11:33 AM
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
9:11:33 AM
THREE.WebGLRenderer: OES_texture_float extension not supported.
9:11:33 AM
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
9:11:33 AM
THREE.WebGLRenderer: OES_texture_half_float extension not supported.
9:11:33 AM
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
9:11:33 AM
THREE.WebGLRenderer: OES_standard_derivatives extension not supported.
9:11:33 AM
THREE.WebGLRenderer: ANGLE_instanced_arrays extension not supported.
9:11:33 AM
THREE.WebGLRenderer: OES_element_index_uint extension not supported.
9:11:33 AM
THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported.
``` 

I'm running the latest XDE (2.17.0) and Expo app (1.15.2.107331).  Both of these just updated this morning, so I'm wondering if perhaps the new versions have breaking changes

**Comment by EvanBacon** [comment]
Oops, I forgot. The simulator doesn't run gl well. Most if not all of those errors look like warnings, they shouldn't effect the app actually running. I'll try and get an older device to test on 🐣

**Comment by Traviskn** [comment]
Well, I just grabbed my wife's iPhone 7 and it works without any issues!  Too bad my poor old 6 can't cut it, guess it's time for an upgrade 😅
